from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from magsim.core.types import AbilityName, RacerName

RACER_ABILITIES: dict[RacerName, set[AbilityName]] = {
    "Alchemist": {"AlchemistAlchemy"},
    "Baba": {"BabaIsTrip"},
    "Banana": {"BananaTrip"},
    "Blimp": {"BlimpModifierManager"},
    "Centaur": {"CentaurTrample"},
    "Cheerleader": {"CheerleaderSupport"},
    "Coach": {"CoachAura"},
    "Lulu": {"CopyLead"},
    "Ludomingo": {"LudomingoRerollManager"},
    "Duelist": {"DuelistDuel"},
    "Cloudgirl": {"CloudgirlCopy"},
    "FlipFlop": {"FlipFlopSwap"},
    "ForbiddenBook": {"ForbiddenBookIncinerate"},
    "Tabetha": {"TabethaPrediction"},
    "Gunk": {"GunkSlime"},
    "Gymnast": {"GymnastCartwheel"},
    "Hare": {"HareHubris"},
    "Halcyon": {"HalcyonModifierManager"},
    "Heckler": {"HecklerHeckle"},
    "HugeSable": {"HugeSablePush"},
    "Hypnotist": {"HypnotistWarp"},
    "Inchworm": {"InchwormCreep"},
    "Lackey": {"LackeyLoyalty"},
    "Leaptoad": {"LeaptoadJumpManager"},
    "Legs": {"LongLegs"},
    "Lyrebird": {"LyrebirdBonus"},
    "Magician": {"MagicalReroll"},
    "Fate": {"FatePredict"},
    "Mouth": {"MouthSwallow"},
    "Dreamybird": {"DreamyPull", "DreamyBoostManager"},
    "Romantic": {"RomanticMove"},
    "RocketScientist": {"RocketScientistBoost"},
    "Scoocher": {"ScoochStep"},
    "Shoe": {"ShoeLaced"},
    "Sisyphus": {"SisyphusCurse"},
    "Skipper": {"SkipperTurn"},
    "Stickler": {"SticklerStrictFinishManager"},
    "Suckerfish": {"SuckerfishRide"},
    "ThirdWheel": {"ThirdWheelJoin"},
    "TreadmillBike": {"TreadmillBikeSpeedUp"},
    "Nina": {"NinaCopy"},
}
